
<div class="container main-container headerOffset"> 
    <div class="w100 clearfix category-top">
                
                <div class="categoryImage"> <img src="<?php echo $this->basePath('img/sucursal/no-image.jpg') ?>" class="img-responsive" alt="img"> </div>
            </div>
    <div class="panel panel-default">
         
        <div id="collapse2" class="panel-collapse collapse in">
            <div class="panel-body">
                <form class="form-horizontal" action="<?php echo $this->url('catalog', array('controller' => 'franchise', 'action' => 'list')) ?>" method="post" >
                    <fieldset>
                        <h2> Busca tu franquicia preferida</h2>
                       
<!--                            <div class="col-md-3">
                                <select id="selectbasic" name="selectbasic" class="form-control">
                                    <option value="0" selected>Seleccione Ciudad</option>
                                    <option value="1">Ciudad #1</option>
                                    <option value="2">Ciudad #2</option>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <select id="selectbasic" name="selectbasic" class="form-control">
                                    <option value="0" selected>Seleccione Zona</option>
                                    <option value="1">Zona #1</option>
                                    <option value="2">Zona #2</option>
                                </select>
                            </div>-->
                            <div class="col-md-4">
                                 <?php echo $this->formSelect($this->form->get('category_id')->setAttributes(['class' => 'form-control'])); ?>
                            </div>
                           
                                                   

                            <div class="col-md-4">
                                <input id="textinput" class="form-control input-md" type="text" placeholder="Nombre de franquicia" name="name"></input>
                                <span class="help-block"></span>
                            </div>
                            <div class="col-md-12">
                                <center>
                                    <button id="button2id" class="btn btn-default" name="button2id">Buscar</button>
                                </center>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div> 	
    <!-- /.row  -->
    <div class="w100 productFilter clearfix">
        <h4 class="pull-left"> Mostrando <strong><?php echo $this->franchieses->count() ?></strong> franquicias </h4>
    </div>
    <div class="row  categoryProduct xsResponse clearfix">
        <?php foreach ($this->franchieses as $franchies) : ?>
        <div class="item col-sm-4 col-lg-4 col-md-4 col-xs-6">
            <div class="product">
                <div class="image">  
                    <div class="quickview">
                    <!--a title="Ver más" class="btn btn-xs  btn-quickview" data-target="#product-details-modal" data-toggle="modal"> Ver más </a-->
                    </div><a href="<?php echo $this->basePath() . '/catalog/branch/list/' . $franchies->franchise_id; ?>">
                        <img src="<?php echo $this->basePath().'/img/franchise/'.$franchies->logo?>" alt="img" class="img-responsive">
                    </a>
                    <!--div class="promotion"> <span class="new-product"> NEW</span> <span class="discount">15% OFF</span> </div-->
                </div>
                <div class="description">
                    <h4><a href="<?php echo $this->basePath() . '/catalog/branch/list/' . $franchies->franchise_id; ?>"><?php echo $franchies->name ?></a></h4>
                    <div class="grid-description">
                        <p>Descripción Breve</p>
                    </div>
                    <div class="list-description">
                        <p> Sed sed rutrum purus. Descripción BrevePellentesque risus lacus, iaculis in ante vitae, viverra hendrerit ante. Aliquam vel fermentum elit. Morbi rhoncus, neque in vulputate facilisis, leo tortor sollicitudin odio, quis pellentesque lorem nisi quis enim. In dolor mi, hendrerit at blandit vulputate, congue a purus. Sed eget turpis sit amet orci euismod accumsan. Praesent sit amet placerat elit. </p>
                    </div>
                </div>
                <div class="action-control">
                    <a class="btn btn-primary" href="<?php echo $this->basePath() . '/catalog/branch/list/' . $franchies->franchise_id; ?>">
                        <span class="add2cart"><i class="glyphicon glyphicon-arrow-right"> </i> Entrar </span>
                    </a>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
    <!--/.categoryProduct || product content end-->
    <!--div class="w100 categoryFooter">
        <div class="pagination pull-left no-margin-top">
            <ul class="pagination no-margin-top">
                <li> <a href="#">«</a></li>
                <li class="active"><a href="#">1</a></li>
                <li> <a href="#">2</a></li>
                <li> <a href="#">3</a></li>
                <li> <a href="#">4</a></li>
                <li> <a href="#">5</a></li>
                <li> <a href="#">»</a></li>
            </ul>
        </div-->
        <!--div class="pull-right pull-right col-sm-4 col-xs-12 no-padding text-right text-left-xs">
        <p>Showing 1–450 of 12 results</p>
    </div-->
</div>
<!-- /main container -->
<div class="gap"></div>