<section id="content" class="table-layout animated fadeIn">
    <!-- begin: .tray-center -->
    <div class="tray tray-center p25 va-t posr">
        <!-- create new order panel -->
        <div class="panel mb25 mt5">
            <div class="panel-heading">
                <span class="panel-title">Orden #</span>
            </div>
            <div class="panel-body p20 pb10">
                <div class="tab-content pn br-n admin-form">
                    <div id="tab1_1" class="tab-pane active">
                        <div class="section row mbn">
                            <div class="col-md-12 pl15">
                                <div class="section row mb15">
                                    <div class="col-xs-6">
                                        <label for="name1" class="field prepend-icon">
                                            Numero de Factura <br>
                                            <b> <?php echo $this->order->invoice_number_branch ?> </b>
                                        </label>
                                    </div>
                                    <div class="col-xs-6">
                                        <label for="name2" class="field prepend-icon">
                                            Fecha de Solicitud <br>
                                            <b><?php echo $this->order->ob_date_added ?></b>
                                        </label>
                                    </div>
                                </div>
                                <div class="section row mb15">
                                    <div class="col-xs-6">
                                        <label for="password" class="field prepend-icon">
                                            Sub Total <br>
                                            <b><?php echo number_format((float) $this->order->subtotal, 2, '.', '') ?></b>
                                        </label>
                                    </div>
                                </div>
                                <div class="section row mb15">
                                    <div class="col-xs-6">
                                        <label for="password" class="field prepend-icon">
                                            Nombre del comprador <br>
                                            <b><?php echo $this->order->firstname ?></b>
                                        </label>
                                    </div>
                                    <div class="col-xs-6">
                                        <label for="password2" class="field prepend-icon">
                                            Apellido del Comprador <br>
                                            <b><?php echo $this->order->lastname ?></b>
                                        </label>
                                    </div>
                                </div>
                                <div class="section row mb15">
                                    <div class="col-xs-6">
                                        <label for="password" class="field prepend-icon">
                                            Email del Comrpador <br>
                                            <b><?php echo $this->order->email ?></b>
                                        </label>
                                    </div>
                                    <div class="col-xs-6">
                                        <label for="password2" class="field prepend-icon">
                                            Cedula de Identidad <br>
                                            <b><?php echo $this->order->document_identity ?></b>
                                        </label>
                                    </div>
                                </div>
                                <div class="section row mb15">
                                    <div class="col-xs-6">
                                        <label for="password" class="field prepend-icon">
                                            Dirección: <br>
                                            <b><?php echo $this->order->address_1 ?></b>
                                        </label>
                                    </div>
                                    <div class="col-xs-6">
                                        <label for="password2" class="field prepend-icon">
                                            Numero Telefonico <br>
                                            <b><?php echo $this->order->telephone ?></b>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end section row -->

                    </div>
                </div>
            </div>
        </div>

        <!-- recent orders table -->
        <div class="panel">
            <div class="panel-body pn">
                <table class="table admin-form">
                    <thead>
                        <tr class="bg-light">
                            <td class="">Nombre</td>
                            <td class="">Descripcion</td>
                            <td class="text-right"></td>

                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $contadorP = 0;
                        $contadorO = 0;
                        ?>
                        <?php foreach ($this->product_order as $product): ?>
                            <tr>
                                <td style="width: 40%">
                                    <a data-remote="true" href="<?php echo '#sub_categoria_' . $contadorO ?>" id="<?php 'categoria' . $contadorP ?>" data-toggle="collapse" data-parent="<?php echo '#sub_categoria_' . $contadorO ?>" style="text-decoration: none; color: black">
                                        <span style="margin-left: 25px;"><?php echo $product->name ?></span>
                                        <span class="menu-ico-collapse"><i class="fa fa-chevron-down"></i></span>
                                    </a>

                                    <div class="collapse list-group-submenu" id="<?php echo 'sub_categoria_' . $contadorO ?>">                                        
                                        <?php foreach ($this->product_option as $option): ?>
                                            <?php if ($option->order_product_id == $product->order_product_id) : ?>
                                                <?php if ($option->nameO): ?>
                                                    <span data-parent="<?php echo '#sub_categoria_' . $contadorO ?>" style="padding-left: 40px;"><?php echo $option->opcion ?>: <b><?php echo $option->nameO ?></b></span><br>
                                                <?php else: ?>
                                                    <span data-parent="<?php echo '#sub_categoria_' . $contadorO ?>" style="padding-left: 40px;"><b>Sin Opciones</b></span><br>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endforeach ?>
                                    </div>  
                                </td>
                                <td class=""><?php echo $product->description ?></td>
                            </tr>
                            <?php
                            $contadorO = $contadorO + 1;
                            $contadorP = $contadorP + 1;
                            ?>
                        <?php endforeach; ?>
                    </tbody>                   
                </table>
            </div>
        </div>

    </div>

</section>
<!--<div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Opciones del Producto
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel"></h4>
            </div>
            <div class="modal-body">
                <div class="panel">
                    <div class="panel-body pn">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <td>Nombre del Producto</td>
                                    <td>Tipo de opcion</td>
                                    <td>Nombre de la Opcion</td>
                                    <td>Precio</td>
                                </tr>
                            </thead>
                            <tbody>
<?php // foreach($this->product_option as $product):      ?>
                                <tr>
                                    <td><?php // echo $product->name                  ?></td>
                                    <td><?php // echo $product->name_option                  ?></td>
                                    <td><?php // echo $product->name_option_value                 ?></td>
                                    <td><?php // echo $product->price_option               ?></td>
                                </tr>
<?php // endforeach;      ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>-->
<script type="text/javascript">
    jQuery(document).ready(function () {

        "use strict";

        // Init Theme Core    
        Core.init();

        // Init Demo JS    
        Demo.init();

        $('#exampleModal1').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var recipient = button.data('whatever') // Extract info from data-* attributes
            // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
            // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
            var modal = $(this)
            modal.find('.modal-title').text(recipient)
        });


    });
</script>