
<!-- End: Main -->
<div id="main" class="animated fadeIn">

    <!-- Start: Content-Wrapper -->
    <section id="content_wrapper">
        <!-- Begin: Content -->
        <section id="content">

            <div class="admin-form theme-info" id="login1">

                <div class="row mb15 table-layout">

                    <div class="col-xs-6 va-m pln">
                        <a href="dashboard.html" title="Return to Dashboard">
                           <img src="<?php echo $this->basePath('img') ?>/logo5.png" title="PideRapido Logo" class="img-responsive w250">
                        </a>
                    </div>
                </div>

                <div class="panel panel-info mt10 br-n">
                    <!-- end .form-header section -->
                    <form method="post" action="<?php echo $this->basePath($this->loginForm->getAttribute('action')); ?>" id="contact">
                        <div class="panel-body bg-light p30">
                            <div class="row">
                                <div class="col-sm-7 pr30">
                                    <div class="section">
                                        <label for="username" class="field-label text-muted fs18 mb10">Usuario</label>
                                        <label for="username" class="field prepend-icon">
                                            <?php echo $this->formInput($this->loginForm->get('email')); ?>
                                            <label for="username" class="field-icon"><i class="fa fa-user"></i>
                                            </label>
                                        </label>
                                    </div>
                                    <!-- end section -->

                                    <div class="section">
                                        <label for="username" class="field-label text-muted fs18 mb10">Password</label>
                                        <label for="password" class="field prepend-icon">
                                            <?php echo $this->formInput($this->loginForm->get('password')); ?>
                                            <label for="password" class="field-icon"><i class="fa fa-lock"></i>
                                            </label>
                                        </label>
                                    </div>
                                    <!-- end section -->

                                </div>
                                <div class="col-sm-5 br-l br-grey pl30">
                                    <center>
                                        <h3 class="mb25">
                                            <img src="<?php echo $this->basePath('img') ?>/logo2.png">
                                        </h3>
                                        <p class="mb15">
                                            En caso de problemas, favor contactar soporte@piderapido.com
                                        </p>
                                    </center>
                                </div>
                            </div>
                        </div>
                        <!-- end .form-body section -->
                        <div class="panel-footer clearfix p10 ph15">
                            <button type="submit" class="button btn-primary mr10 pull-right">Ingresar</button>
                            <?php echo $this->formInput($this->loginForm->get('csrf')); ?>
<!--                            <label class="switch block switch-primary pull-left input-align mt10">
                            <?php // echo $this->formInput($this->loginForm->get('rememberme')); ?>
                            <label for="remember" data-on="YES" data-off="NO"></label>
                            Recordarme 
                            </label>-->
                        </div>
                        <!-- end .form-footer section -->
                    </form>
                </div>
            </div>

        </section>
        <!-- End: Content -->

    </section>
    <!-- End: Content-Wrapper -->

</div>
<!-- BEGIN: PAGE SCRIPTS -->
