

<section id="content" class=" pnanimated fadeIn">

    <h2 class="lh30 mt15 text-center"> Crear <b class="text-primary"> Franquicia </b></h2>

    <!-- Admin-panels -->
    <div class="admin-panels fade-onload sb-l-o-full">

        <div class="row">
            <form id="form"  action="<?php echo $this->basePath($this->form->getAttribute('action')); ?>" method="post" enctype="multipart/form-data" >   
                <div class="tray tray-center p25 va-t posr">

                    <!-- Store Owner Details -->
                    <div class="panel">
                        <div class="panel-heading">
                            <span class="panel-title">Franquicia</span>
                        </div>
                        <div class="panel-body bg-light dark">
                            <div class="admin-form col-xs-5">
                                <div class="section row mb10">
                                    <label for="account-name" class="field-label col-md-3 text-center">Nombre:</label>
                                    <div class="col-md-9">
                                        <label for="account-name" class="field prepend-icon">
                                            <?php echo $this->formInput($this->form->get('name')); ?>
                                            <label for="account-name" class="field-icon"><i class="fa fa-male"></i>
                                            </label>
                                        </label>
                                    </div>
                                </div>
                                <div class="section row mb10">
                                    <label for="account-email" class="field-label col-md-3 text-center">RIF:</label>
                                    <div class="col-md-9">
                                        <label for="account-email" class="field prepend-icon">
                                            <?php echo $this->formInput($this->form->get('rif')); ?>
                                            <label for="account-email" class="field-icon"><i class="fa fa-envelope-o"></i>
                                            </label>
                                        </label>
                                    </div>
                                </div>
                                <div class="section row mb10">
                                    <label for="account-name" class="field-label col-md-3 text-center">Dirección Fiscal: </label>
                                    <div class="col-md-9">
                                        <label for="account-name" class="field prepend-icon">
                                            <?php echo $this->formInput($this->form->get('address')); ?>
                                            <label for="account-name" class="field-icon"><i class="fa fa-home"></i>
                                            </label>
                                        </label>
                                    </div>
                                </div>
                               <div class="section row mb10">
                                    <label for="account-name" class="field-label col-md-3 text-center">Categoria: </label>
                                    <div class="col-md-9">
                                        <label for="pais" class="field select">
                                            <?php echo $this->formSelect($this->form->get('category_id')); ?>
                                            <i class="arrow double"></i>
                                        </label>

                                    </div>
                                </div>
                            </div>
                            <div class="admin-form col-xs-5">
                                <div class="section row mb10">
                                    <label for="account-name" class="field-label col-md-3 text-center">Telefono: </label>
                                    <div class="col-md-9">
                                        <label for="account-name" class="field prepend-icon">
                                            <?php echo $this->formInput($this->form->get('telephone')); ?>
                                            <label for="city" class="field-icon"><i class="fa fa-phone"></i>
                                            </label>
                                        </label>
                                    </div>
                                </div>
                                <div class="section row mb10">
                                    <label for="account-name" class="field-label col-md-3 text-center">País: </label>
                                    <div class="col-md-9">
                                        <label for="pais" class="field select">
                                            <?php echo $this->formSelect($this->form->get('country')); ?>
                                            <i class="arrow double"></i>
                                        </label>

                                    </div>
                                </div>

                                <div class="section row mb10">
                                    <label for="account-name" class="field-label col-md-3 text-center">Estado: </label>
                                    <div class="col-md-9">
                                        <label for="account-name" class="field prepend-icon">
                                            <?php echo $this->formInput($this->form->get('state')); ?>
                                            <label for="city" class="field-icon"><i class="fa fa-building-o"></i>
                                            </label>
                                        </label>
                                    </div>
                                </div>

                                <div class="section row mb10">
                                    <label for="account-name" class="field-label col-md-3 text-center">Municipio: </label>
                                    <div class="col-md-9">
                                        <label for="account-name" class="field prepend-icon">
                                            <?php echo $this->formInput($this->form->get('city')); ?>
                                            <label for="zip" class="field-icon"><i class="fa fa-home"></i>
                                            </label>
                                        </label>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-2">
                                <div class="fileupload fileupload-new admin-form" data-provides="fileupload">
                                    <div class="fileupload-new thumbnail" style="">
                                        <img data-src="holder.js/100%x147/text:logo" alt="holder">
                                    </div>
                                    <div class="fileupload-preview fileupload-exists thumbnail" style=""></div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <span class="button btn-system btn-file btn-block">
                                                <span class="fileupload-new">Select</span>
                                                <span class="fileupload-exists">Change</span>
                                                <?php echo $this->formFile($this->form->get('logo')); ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="admin-form col-xs-12">
                            <div class="section row mb10">
                                <label class="field prepend-icon append-button file">
                                    <span class="button">Subir Archivo</span>
                                     <?php echo $this->formFile($this->form->get('banner')->setAttributes(['onChange' => "document.getElementById('uploader1').value = this.value;", 'class' => 'gui-file'])); ?>
                                    
                                    <input type="text" class="gui-input" id="uploader1" placeholder="Cambiar Banner (Tamaño: 1200 x 350)">
                                    <label class="field-icon"><i class="fa fa-upload"></i>
                                    </label>
                                </label>
                                <s
                            </div>
                        </div>
                    <div class="col-md-offset-9">

                        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                        <input class="btn btn-danger" type="button" onclick="history.back(-1)" value="Cancelar">
                    </div>    
                </div>
            </form>                     
        </div>

    </div>

</section> 

<?php
$this->headScript()
        // Admin Panels
        ->prependFile($this->basePath('assets_admin') . '/admin-tools/admin-plugins/admin-panels/json2.js')
        ->prependFile($this->basePath('assets_admin') . '/admin-tools/admin-plugins/admin-panels/jquery.ui.touch-punch.min.js')
        ->prependFile($this->basePath('assets_admin') . '/admin-tools/admin-plugins/admin-panels/adminpanels.js')
        // Page Plugins via CDN 
        ->prependFile('http://cdnjs.cloudflare.com/ajax/libs/globalize/0.1.1/globalize.min.js')
        ->prependFile('http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.3/moment.js')
        // Sparklines CDN
        ->prependFile('http://cdnjs.cloudflare.com/ajax/libs/jquery-sparklines/2.1.2/jquery.sparkline.min.js')
        //Page Plugins
        ->prependFile($this->basePath('vendor') . '/plugins/daterange/daterangepicker.js')
        ->prependFile($this->basePath('vendor') . '/plugins/datepicker/js/bootstrap-datetimepicker.min.js')
        ->prependFile($this->basePath('vendor') . '/plugins/tagmanager/tagmanager.js')
        // Chart Plugins
        ->prependFile($this->basePath('vendor') . '/plugins/highcharts/highcharts.js')
        ->prependFile($this->basePath('vendor') . '/plugins/circles/circles.js')
        ->prependFile($this->basePath('vendor') . '/plugins/raphael/raphael.js')
        // Holder js
        ->prependFile($this->basePath() . '/vendor/plugins/fileupload/fileupload.js')
        ->prependFile($this->basePath('assets_admin') . '/js/bootstrap/holder.min.js')
;



$this->inlineScript()->captureStart();
echo <<<JS
   jQuery(document).ready(function() {


            $('.admin-panels').adminpanel({
                grid: '.admin-grid',
                draggable: true,
                preserveGrid: true,
                mobile: false,
                callback: function() {
                    bootbox.confirm('<h3>A Custom Callback!</h3>', function() {});
                },
                onFinish: function() {
                    $('.admin-panels').addClass('animated fadeIn').removeClass('fade-onload');

                    // Init the rest of the plugins now that the panels
                    // have had a chance to be moved and organized.
                    // It's less taxing to organize empty panels
                    demoHighCharts.init();
                    runVectorMaps();

                    // We also refresh any "in-view" waypoints to ensure
                    // the correct position is being calculated after the 
                    // Admin Panels plugin moved everything
                    Waypoint.refreshAll();

                },
                onSave: function() {
                    $(window).trigger('resize');
                }
            });

          
            // Init custom page animation
            setTimeout(function() {
                $('.custom-nav-animation li').each(function(i, e) {
                    var This = $(this);
                    var timer = setTimeout(function() {
                        This.addClass('animated animated-short zoomIn');
                    }, 50 * i);
                });
            }, 500);

            // Init tray navigation smooth scroll
            $('.tray-nav a').smoothScroll({
                offset: -145
            });
            

           
        });

JS;
$this->inlineScript()->captureEnd();
