<div class="container main-container"> 
  
  <!-- Main component call to action -->
  
  <div class="morePost row featuredPostContainer style2 globalPaddingTop ">
    <h3 class="section-title style2 text-center"><span>Productos Destacados</span></h3>
    <div class="container">
      <div class="row xsResponse">
       
        <!--/.item-->
       
        <?php foreach ($this->lastProduct as $product) : ?>
            <div class="item col-sm-3 col-lg-3 col-md-3 col-xs-6">
                <div class="product">
                    <div class="image">
                        <div class="quickview">
                            <!--a title="Quick View" class="btn btn-xs  btn-quickview" data-target="#product-details-modal" data-toggle="modal"> Quick View </a-->
                        </div>
                        <a href="<?php echo $this->url('catalog', array('controller' => 'branch', 'action' => 'product', 'id' => $product->product_has_branch_id)); ?>"><img src="<?php echo $this->basePath() . '/img/catalog/product/' . $product->image ?>" alt="img" class="img-responsive"></a>
                        <div class="promotion">
                            <span class="new-product"> Nuevo </span>
                        </div>
                    </div>
                    <div class="description">
                        <h4><a href="<?php echo $this->url('catalog', array('controller' => 'branch', 'action' => 'product', 'id' => $product->product_has_branch_id)); ?>"><?php echo $product->name ?></a></h4>
                        <div class="grid-description">
                            <p><?php echo $product->description ?></p>
                        </div>
                    </div>
                    <div class="action-control">
                        <a class="btn btn-primary" href="<?php echo $this->url('catalog', array('controller' => 'cart', 'action' => 'add', 'id' => $product->product_has_branch_id)); ?>">
                            <span class="add2cart"><i class="glyphicon glyphicon-shopping-cart"></i> Añadir al carrito</span>
                        </a>
                    </div>
                </div>
            </div>   
        <?php endforeach; ?>
       
      </div>
      <!-- /.row -->
      
      <!--div class="row">
        <div class="load-more-block text-center"> <a class="btn btn-thin" href="#"> <i class="fa fa-plus-sign">+</i> Ver más</a> </div>
      </div-->
    </div>
    <!--/.container--> 
  </div>
  </div>
  <!--/.featuredPostContainer-->
