<div class="parallax-section parallax-image-1">
  <div class="container">
    <div class="row ">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="parallax-content clearfix">
       
          <h2 class="uppercase">¡Encuéntralo!</h2><br>
          <h3> Elige qué quieres comer y dónde, que nosotros lo buscamos por ti</h3>
          <div style="clear:both"></div>
			<a class="btn btn-discover" href="<?php echo $this->url('catalog', array('controller' => 'franchise', 'action' => 'list')) ?>"> <i class="fa fa-shopping-cart"></i> Buscar </a> 
		</div>
      </div>
    </div>
    <!--/.row--> 
  </div>
  <!--/.container--> 
</div>