<div class="parallax-section parallax-image-2">
  <div class="w100 parallax-section-overley">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="parallax-content clearfix">
            <h1 class="xlarge">¡Aumenta tu saldo!</h1>
            <h5 class="parallaxSubtitle"> Abona dinero a tu cuenta de Pide Rápido para realizar transacciones de manera más rápida </h5>
			 <a class="btn btn-discover" href="micuenta.php"> <i class="fa fa-shopping-cart"></i> Comprar </a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>