<div class="banner" style="margin-top:1px">
  <div class="full-container">
    <div class="slider-content">
      <ul id="pager" class="container">
      </ul>
      <div class="slider slider-v2">
        <div class="slider-item slider-item-img1 " data-cycle-pager-template="<a href=#> franquicias </a>">
          <div class="sliderInfo">
            <div class="container">
              <div class="col-lg-5 col-md-5 col-sm-5 pull-right sliderText dark alpha80 hidden-xs">
                <div class="inner">
                  <h1>Buscar por Franquicia</h1>
                  <p class="hidden-xs">Las cadenas de alimentos mas populares confían en Pide Rápido, busca la que mas te provoque y haz tu pedido sin hacer cola. </p>
<!--                  <a href="buscafranquicia.php" class="slide-link">Buscar <span class="arrowUnicode">►</span></a> -->
                  </div>
              </div>
            </div>
          </div>
          <img alt="img" src="<?php echo $this->basePath('img') ?>/slider/sp1.jpg" class="img-responsive parallaximg sliderImg"> </div>
        
        <div class="slider-item slider-item-img2  parallax" data-cycle-pager-template="<a href=#> Ciudad </a>">
          <div class="sliderInfo">
            <div class="container">
              <div class="col-lg-5 col-md-5 col-sm-5 pull-left sliderText dark alpha80 hidden-xs">
                <div class="inner">
                  <h1>Buscar por Ciudad</h1>
                  <p class="hidden-xs">Averigua qué locales de tu ciudad están suscritos a nuestra plataforma.</p>
<!--                  <a href="buscaciudad.php" class="slide-link">Buscar <span class="arrowUnicode">►</span></a> -->
                  </div>
              </div>
            </div>
          </div>
          <img alt="img" src="<?php echo $this->basePath('img') ?>/slider/sp2.jpg" class="img-responsive parallaximg sliderImg"> </div>
        
        <div class="slider-item slider-item-img3  parallax" data-cycle-pager-template="<a href=#> Promociones </a>">
          <div class="sliderInfo">
            <div class="container">
              <div class="col-lg-4 col-md-4 col-sm-5 pull-right sliderText dark alpha80 transformRight hidden-xs">
                <div class="inner">
                  <h1> Promociones</h1>
                  <p class="hidden-xs">Ahorra dinero y disfruta de las promociones que Pide Rápido trae para ti</p>
<!--                  <a href="buscapromociones.php" class="slide-link">Buscar<span class="arrowUnicode">►</span></a> -->
                  </div>
              </div>
            </div>
          </div>
          <img alt="img" src="<?php echo $this->basePath('img') ?>/slider/sp4.jpg" class="img-responsive parallaximg sliderImg"> </div>
		  
		  <div class="slider-item slider-item-img3  parallax" data-cycle-pager-template="<a href=#> Programar Pedidos </a>">
          <div class="sliderInfo">
            <div class="container">
              <div class="col-lg-4 col-md-4 col-sm-5 pull-right sliderText dark alpha80 transformRight hidden-xs">
                <div class="inner">
                  <h1> Programar Pedidos</h1>
                  <p class="hidden-xs">Ahorra dinero y disfruta de las promociones que Pide Rápido trae para ti</p>
<!--                  <a href="comofunciona.php#programados" class="slide-link">Ver más<span class="arrowUnicode">►</span></a>-->
                  </div>
              </div>
            </div>
          </div>
          <img alt="img" src="<?php echo $this->basePath('img') ?>/slider/sp3.jpg" class="img-responsive parallaximg sliderImg"> </div>
      </div>
    
	</div>
    <!--/.slider-content--> 
  </div>
  <!--/.full-container--> 
</div>
<!--/.banner style2-->