<div>
    <div>  
        <table style="width:100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f6f4f5">
            <tbody>
                <tr>
                    <td>
                        <table style="width:580px;margin-top: 15px;" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"><tbody><tr><td style="background-color: #a91220;">
                                        <table style="width:280px" border="0" cellspacing="0" cellpadding="0" align="left"><tbody><tr><td style="padding:15px 0 15px 20px" width="270">
                                                        <div><a href="http://piderapido.com" target="_blank"><img style="border:none;text-decoration:none" src="http://piderapido.com/img/logo5.png" alt="logo" border="0" class="CToWUd"></a></div>
                                                    </td>
                                                </tr></tbody></table></td>
                                </tr></tbody></table></td>
                </tr></tbody></table></div>
    <div>
        <table style="width:100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f6f4f5"><tbody><tr><td>
                        <table style="width:580px;margin-bottom: 15px" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"><tbody><tr><td width="100%" height="20">&nbsp;</td>
                                </tr><tr><td>
                                        <table style="width:540px" border="0" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:34px;color:#245273;text-align:center;line-height:34px">Contacto!</td>
                                                        </tr><tr><td>
                                                                <ul>
                                                                    <li><b>Nombre :</b><?php echo $this->comment->name ?></li>
                                                                    <li><b>email :</b><?php echo $this->comment->email ?></li>
                                                                    <li><b>Telefono :</b><?php echo $this->comment->phone ?></li>
                                                                    <li><b>Asunto :</b><?php echo $this->comment->subject ?></li>
                                                                    <li><b>Fecha :</b><?php echo $this->comment->date_added ?></li>
                                                                    <li><b>Comentario :</b><?php echo $this->comment->comment ?></li>
                                                                    
                                                                </ul>
                                                    </td>
                                                </tr><tr><td width="100%" height="20">&nbsp;</td>
                                                </tr><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:11px;color:#666666;text-align:left;line-height:11px">En caso de recibir este mensaje por error, no es necesario tomar ninguna otra medida, no recibirá ningún envío automatizado. Si cree que su dirección de correo electrónico fue mal utilizado, por favor contacte con nosotros en <a href="mailto:info@piderapido.com" target="_blank">info@piderapido.com</a>.</td>
                                                </tr><tr><td width="100%" height="20">&nbsp;</td>
                                                </tr></tbody></table></td>
                                </tr></tbody></table></td>
                </tr></tbody></table></div>
</div>