<div>
    <div>  
        <table style="width:100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f6f4f5">
            <tbody>
                <tr>
                    <td>
                        <table style="width:580px;margin-top: 15px;" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"><tbody><tr><td style="background-color: #a91220;">
                                        <table style="width:280px" border="0" cellspacing="0" cellpadding="0" align="left"><tbody><tr><td style="padding:15px 0 15px 20px" width="270">
                                                        <div><a href="http://piderapido.com" target="_blank"><img style="border:none;text-decoration:none" src="http://piderapido.com/img/logo5.png" alt="Pide Rapido" border="0" class="CToWUd"></a></div>
                                                    </td>
                                                </tr></tbody></table></td>
                                </tr></tbody></table></td>
                </tr></tbody></table></div>
    <div>
        <table style="width:100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f6f4f5"><tbody><tr><td>
                        <table style="width:580px;margin-bottom: 15px" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"><tbody><tr><td width="100%" height="20">&nbsp;</td>
                                </tr><tr><td>
                                        <table style="width:540px" border="0" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:34px;color:#245273;text-align:center;line-height:34px">¡Bienvenido(a) <?php echo ucfirst($this->operator->name) ?>!</td>
                                                </tr><tr>
                                                </tr><tr><td width="100%" height="20">&nbsp;</td>
                                                </tr><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:13px;color:#666666;text-align:left;line-height:18px">
                                                        <p>Desde Pide Rápido queremos darte las gracias por elegirnos como tu aliado en ventas ON-LINE.<br><br>Estos son tus datos para iniciar sesion:</p>
                                                        <p>Usuario: <?php echo ucfirst($this->operator->email) ?></p>
                                                        <p>Constraseña: <?php echo ucfirst($this->contraseña) ?></p><br>
                                                        <p>Ya estás más cerca de  empezar a vender de una manera innovadora.</p><br>
                                                    </td>
                                                </tr><tr><td width="100%" height="20">&nbsp;</td>
                                                </tr><tr><td width="100%" height="20">&nbsp;</td>
                                                </tr><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:13px;color:#666666;text-align:left;line-height:18px">
                                                        <p><span style="color:#666666;font-family:Helvetica,arial,sans-serif;font-size:13px;line-height:18px">¡Así de fácil, rápido y cómodo!</span>,<br> El equipo de Pide<strong>Rapido</strong>.com</p>
                                                    </td>
                                                </tr><tr><td width="100%" height="20">&nbsp;</td>
                                                </tr><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:11px;color:#666666;text-align:left;line-height:11px">Si tienes alguna pregunta por favor escríbenos a <a href="mailto:soporte@piderápido.com" target="_blank">soporte@piderápido.com</a>.</td>
                                                </tr><tr><td width="100%" height="20">&nbsp;</td>
                                                </tr></tbody></table></td>
                                </tr></tbody></table></td>
                </tr></tbody></table></div>
</div>