<div class="w100 clearfix category-top">

                <h1>Cómo funciona</h1>

                <div class="categoryImage"> <img src="<?php echo $this->basePath('img/sucursal/no-image.jpg') ?>" class="img-responsive" alt="img"> </div>

            </div>

<!-- /.parallax -->

<div class="container main-container">  

    <div class="row innerPage">

        <div class="col-lg-12 col-md-12 col-sm-12">

            <div class="row userInfo">

                <div class="col-xs-12 col-sm-12">

                    <!--h1 class="title-big text-center section-title-style2">

                        <span>About us</span>

                    </h1-->          

                    <p class="lead text-center">Vive la experiencia de ser siempre el primero, con Pide Rápido podrás programar tu pedido e indicarnos la hora en la que deseas que esté listo</p>

                    <hr class="hr hr30">

                    <div class="row animated">

                        <div class="col-lg-3 col-md-4 col-sm-6 col-sm-6">

                            <img class="img-responsive" src="<?php echo $this->basePath('img') ?>/comofunciona/paso1.jpg" alt="img">

                            <h3 class="block-title-3">Paso #1</h3>

                            <p>Selecciona la franquicia y local que deseas realizar tu pedido.</p>

                        </div>            

                        <div class="col-lg-3 col-md-4 col-sm-6 col-sm-6">

                            <img class="img-responsive" src="<?php echo $this->basePath('img') ?>/comofunciona/paso2.jpg" alt="img">

                            <h3 class="block-title-3">Paso #2</h3>

                            <p>Selecciona todo los productos que deseas consumir.</p>

                        </div>			

                        <div class="col-lg-3 col-md-4 col-sm-6 col-sm-6">

                            <img class="img-responsive" src="<?php echo $this->basePath('img') ?>/comofunciona/paso3.jpg" alt="img">

                            <h3 class="block-title-3">Paso #3</h3>

                            <p>Haz tu pago online por cualquier medio, tarjeta de Crédito o Débito Banesco.</p>

                        </div>            

                        <div class="col-lg-3 col-md-4 col-sm-6 col-sm-6">

                            <img class="img-responsive" src="<?php echo $this->basePath('img') ?>/comofunciona/paso4.jpg" alt="img">

                            <h3 class="block-title-3">Paso #4</h3>

                            <p>Pide Rápido te avisará cuando tu pedido esté listo y con el código recibido pasas a retirarlo.</p>

                        </div>            

                    </div><!--/.row-->

                    <br><br>

                </div>          

                <hr class="hr hr30">			

                <div class="row">

                    <center>

                        <h1 class="block-title-3">Video Explicativo</h1>

                        <br>

                    </center>

                    <div class="col-lg-12 col-md-4 col-sm-6 col-sm-6">

                        <center>

                            <iframe id="fitvid102089" width="750" height="450" frameborder="0" allowfullscreen="" mozallowfullscreen="" webkitallowfullscreen="" src="http://www.youtube.com/embed/Zv58H2czmN8"></iframe>

                        </center>

                    </div>

                </div><!--/.row-->		  

                <br><br>		  

                <div class="row animated" id="programados">

		            <br><br>

                    <center>

                        <h1 class="block-title-3">Pedidos Programados</h1>

                    </center>			

                    <div class="col-lg-6 col-md-4 col-sm-6 col-sm-6">

                        <img class="img-responsive" src="<?php echo $this->basePath('img') ?>/comofunciona/paso1.jpg" alt="img">

                        <h3 class="block-title-3">Característica #1</h3>

                        <p>Selecciona el menú que deseas.</p>

                    </div>            

                    <div class="col-lg-6 col-md-4 col-sm-6 col-sm-6">

                        <img class="img-responsive" src="<?php echo $this->basePath('img') ?>/comofunciona/paso2.jpg" alt="img">

                        <h3 class="block-title-3">Característica #2</h3>

                        <p>Programa tu pedido, indicando hora que deseas retirarlo.</p>

                    </div>

                </div>

            </div>

        </div>  <!--/row end-->

    </div>

</div> <!--/.innerPage-->