
<div class="wrapper whitebg">
     <div class="w100 map">
        <iframe width="1150" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3923.764240135437!2d-66.83774558475541!3d10.44027386816199!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c2af7dcdd271c5b%3A0xac6e50c7d5e95d3a!2sC.+C.+Galer%C3%ADas+Los+Naranjos!5e0!3m2!1ses!2sve!4v1447695617383"></iframe>
        
    </div>
    <div class="container main-container ">
        <div class="row innerPage">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="row userInfo">
                    <div class="col-xs-12 col-sm-12">
                        <h1 class="title-big text-center section-title-style2"><span> Contáctanos </span></h1>
                       
                        <hr>
                        <div class="row">           
                            <form method="post" action="<?php $this->url('catalog', array('controller' => 'info', 'action' => 'contacto')) ?>" >
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <br>
                                <center>
                                    <h2>Déjanos un mensaje o sugerencia</h2>
                                    <h4>Le responderemos en la brevedad posible</h4>
                                    <br>
                                    <input id="textinput" required="required" class="form-control input-md" type="text" name="name" placeholder="Nombre">
                                    <input id="textinput" required="required" class="form-control input-md" type="text" name="email" placeholder="Email">
                                    <input id="textinput" required="required" class="form-control input-md" type="text" name="phone" placeholder="Teléfono">
                                    <input id="textinput" required="required" class="form-control input-md" type="text" name="subject" placeholder="Asunto">
                                    <textarea id="textarea" class="form-control" name="comment" placeholder="Mensaje"></textarea>
                                    <br>
                                    <button id="singlebutton" class="btn btn-primary" name="singlebutton">Enviar</button>
                                    <br>
                                </center>
                            </div>
                            </form>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    				            <br>
                                <h3 class="block-title-5">
                                    Soporte
                                </h3>
                                <p>
                                    D'Alvano Rapid Company C.A

                                    <br>
                                    Av. Pauji Residencia Serranillo 7B Caracas - Los Naranjos.
                                    <br>
                                    <strong>
                                    Teléfono
                                    </strong>
                                    : +058 0212-435 6474
                                    <br>
                                    <strong>
                                    Email
                                    </strong>
                                    : 	soporte@piderapido.com 
                                </p>
                               
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    				            <br>
                                <h3 class="block-title-5">
                                    Afiliaciones
                                </h3>
                                <p>
                                    Para afiliar tu franquicia a nuestro site comunicate por medio de
                                    <br>
          
                                    <strong>
                                        
                                    Teléfono
                                    </strong>
                                    : +058 0212-435 6474
                                    <br>
                                      <strong>
                                    Email
                                    </strong>
                                    : 	 info@piderapido.com 
                                    
                                    
                                </p>
                               
                            </div>
                            <div style="clear:both"></div>
                        </div><!--/.row-->
               		</div>
                </div> <!--/.row  ||  -->
            </div>
        </div>  <!--/row || innerPage end-->
        <div style="clear:both"></div>
    </div><!-- ./main-container -->
    <div class="gap"></div>
</div>