
<div class="container main-container headerOffset">  
  <!-- Main component call to action --> 
    <div class="row">
        <!--right column-->
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="w100 clearfix category-top">
                <h1><?php echo $this->franchise->name ?></h1>
                <div class="categoryImage"> <img src="<?php echo $this->basePath('img/sucursal/no-image.jpg') ?>" class="img-responsive" alt="img"> </div>
            </div>
            <!--/.category-top-->      
            <div class="row  clearfix">	  
                <br/>
                  <form class="form-horizontal" action="<?php echo $this->url('catalog', array('controller' => 'branch', 'action' => 'list', 'id' => $this->branch_id)) ?>" method="post" >
                    <fieldset>
                <center>
                    <h1>Sucursales afiliadas a <?php echo $this->franchise->name ?></h1>
                    <p> Buscar sucursales filtradas por tu ciudad</p>
                    <br>
                    <div class="form-group">     
                            <div class="col-md-3">

                            </div>
                            <div class="col-md-3">
                                 <?php echo $this->formSelect($this->form->get('city_id')->setAttributes(['class' => 'form-control'])); ?>
                            </div>
                           
                            <div class="col-md-3">
                                <center>
                                    <button id="button2id" class=" left btn btn-default" name="button2id">Buscar</button>
                                </center>
                            </div>
                        </div>
                </center>
                    </fieldset>
                  </form>
            </div>
            <!--/.subCategoryList-->      
            <div class="w100 productFilter clearfix">
        <h4 class="pull-left"> Mostrando <strong><?php echo $this->branch->count() ?></strong> Sucursales </h4>
    </div>
            <!--/.productFilter-->
            <div class="container">
                <div class="row xsResponse">
                    <?php foreach ($this->branch as $branch) : ?>
                    <div class="item col-lg-4 col-md-4 col-sm-4 col-xs-6">
                        <div class="product">
                           
                            
                            <?php if($branch->status == 1) : ?> 
                             <div class="image">  
                                <div class="quickview">
                                <!--a title="Ver combo" class="btn btn-xs  btn-quickview" data-target="#product-details-modal" data-toggle="modal"> Ver combo </a-->
                                </div>
                                <a href="<?php echo $this->basePath() . '/catalog/branch/detail/' . $branch->branch_id; ?>"><br><img src="<?php echo $this->basePath().'/img/franchise/branch/'.$branch->logo?>" alt="img" class="img-responsive"></a>
                            </div>
                            <div class="description">
                                <h4><a href="<?php echo $this->basePath() . '/catalog/branch/detail/' . $branch->branch_id; ?>">Sucursal <?php echo $branch->name ?></a></h4>
                                <p><?php echo $branch->address ?></p>
                                <!--span class="size">XL / XXL / S </span-->
                            </div>
                            <!--div class="price"> <span>$25</span> </div-->
                            <div class="action-control"> 
                                <a class="btn btn-primary" href="<?php echo $this->basePath() . '/catalog/branch/detail/' . $branch->branch_id; ?>"> 
                                    <span class="add2cart"><i class="glyphicon glyphicon-shopping-cart"> </i>  Ir a sucursal  </span>
                                </a> 
                            </div>
                            <?php else : ?>
                            <div class="image">  
                                <div class="quickview">
                                <!--a title="Ver combo" class="btn btn-xs  btn-quickview" data-target="#product-details-modal" data-toggle="modal"> Ver combo </a-->
                                </div>
                               <br><img src="<?php echo $this->basePath().'/img/franchise/branch/'.$branch->logo?>" alt="img" class="img-responsive">
                            </div>
                            <div class="description">
                                <h4>Sucursal <?php echo $branch->name ?></h4>
                                <p><?php echo $branch->address ?></p>
                                <!--span class="size">XL / XXL / S </span-->
                            </div>
                             <div class="action-control"> 
                                <a class="btn btn-primary disabled" href=""> 
                                    <span class="add2cart"><i class="glyphicon glyphicon-alert"> </i>  No Disponible </span>
                                </a> 
                            </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <!--/right column end--> 
        </div>
        <!-- /.row  --> 
    </div>
</div>