<div class="container main-container headerOffset">
	<div class="row innerPage">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<div class="row userInfo">
				<p class="lead text-center"> 
					<img src="<?php echo $this->basePath().'/img/logo2.png'; ?>">
				</p>
                                <h1 class="text-center">Gracias por tu compra! </h1>
				<p class="lead text-center"> 
                                
					¡Recibirás un mensaje en pocos minutos!
					<h5>
					<center>
					 Puede ir al historial de compras en su <a href="<?php echo $this->url('account'); ?>">perfil</a>, para mas detalle.
					</center>
					</h5>
				</p>
				
			</div>  <!--/row end-->
		</div>
	</div> <!--/.innerPage-->
	<div style="clear:both"></div>
</div><!-- /.main-container -->