

            <div class="panel">
<!--                <div class="col-md-4">
                    <div class="panel">
                        <div class="panel-heading">
                            <span class="panel-title">
                                <span class="glyphicons glyphicons-fast_food"></span>Ver Combo</span>
                        </div>
                        <div class="panel-body">

                            <div class="clearfix"></div>
                            <div class="tab-content br-n pn">
                                <div id="tab17_1" class="tab-pane active">
                                    <div class="row">

                                        <div class="col-md-12 text-center">

                                            <a href="<?php // echo $this->url('admin', array('controller' => 'combo', 'action' => 'list-franchise')); ?>" class="holder-style p15" data-steps-style="steps-tabs">
                                                <span class="fa fa-plus holder-icon"></span>
                                                <br> Ver Combos
                                            </a>
                                            <div class="btn-group text-right">
                                            </div>   

                                        </div>
                                    </div>
                                </div>                                    
                            </div>
                        </div>
                    </div>
                </div> -->
                <div class="col-md-4">
                    <div class="panel">
                        <div class="panel-heading">
                            <span class="panel-title">
                                <span class="glyphicons glyphicons-fast_food"></span>Ver Productos</span>
                        </div>
                        <div class="panel-body">
                            <div class="clearfix"></div>
                            <div class="tab-content br-n pn">
                                <div id="tab17_1" class="tab-pane active">
                                    <div class="row">

                                        <div class="col-md-12 text-center">
                                            <a href="<?php echo $this->url('admin', array('controller' => 'product', 'action' => 'listFranchise')); ?>" class="holder-style p15" data-steps-style="steps-tabs">
                                                <span class="fa fa-plus holder-icon"></span>
                                                <br> Ver producto
                                            </a>
                                            <div class="btn-group text-right">
                                            </div>   
                                        </div>
                                    </div>
                                </div>                                    
                            </div>
                        </div>
                    </div>
                </div> 
                <div class="col-md-4">
                    <div class="panel">
                        <div class="panel-heading">
                            <span class="panel-title">
                                <span class="glyphicons glyphicons-fast_food"></span>Ver Opciones</span>
                        </div>
                        <div class="panel-body">
                            <div class="clearfix"></div>
                            <div class="tab-content br-n pn">
                                <div id="tab17_1" class="tab-pane active">
                                    <div class="row">

                                        <div class="col-md-12 text-center">
                                            <a href="<?php echo $this->url('admin', array('controller' => 'product', 'action' => 'listFranchiseProduct')); ?>" class="holder-style p15" data-steps-style="steps-tabs">
                                                <span class="fa fa-plus holder-icon"></span>
                                                <br> Ver ingrediente
                                            </a>
                                            <div class="btn-group text-right">
                                            </div>   
                                        </div>
                                    </div>
                                </div>                                    
                            </div>
                        </div>
                    </div>
                </div> 



            </div>

<?php
$this->headScript()
        // Admin Panels
        ->prependFile($this->basePath('vendor') . '/plugins/datepicker/js/moment.js')
        ->prependFile($this->basePath('assets_admin') . '/admin-tools/admin-plugins/admin-panels/json2.js')
        ->prependFile($this->basePath('assets_admin') . '/admin-tools/admin-plugins/admin-panels/jquery.ui.touch-punch.min.js')
        ->prependFile($this->basePath('assets_admin') . '/admin-tools/admin-plugins/admin-panels/adminpanels.js')
        // Page Plugins via CDN 
        ->prependFile('http://cdnjs.cloudflare.com/ajax/libs/globalize/0.1.1/globalize.min.js')
        
        // Sparklines CDN
        ->prependFile('http://cdnjs.cloudflare.com/ajax/libs/jquery-sparklines/2.1.2/jquery.sparkline.min.js')
        //Page Plugins
        ->prependFile($this->basePath() . '/assets/js/bootstrap.js')
        ->prependFile($this->basePath('vendor') . '/plugins/datepicker/js/moment.js')
        ->prependFile($this->basePath('vendor') . '/plugins/daterange/daterangepicker.js')
        ->prependFile($this->basePath('vendor') . '/plugins/datepicker/js/bootstrap-datetimepicker.min.js')
        ->prependFile($this->basePath('vendor') . '/plugins/tagmanager/tagmanager.js')
        // Chart Plugins
        ->prependFile($this->basePath('vendor') . '/plugins/highcharts/highcharts.js')
        ->prependFile($this->basePath('vendor') . '/plugins/circles/circles.js')
        ->prependFile($this->basePath('vendor') . '/plugins/raphael/raphael.js')
        
        ->prependFile($this->basePath() . '/vendor/plugins/fileupload/fileupload.js')
        ->prependFile($this->basePath('assets_admin') . '/js/bootstrap/holder.min.js')
;
;
$this->inlineScript()->captureStart();
echo <<<JS
    jQuery(document).ready(function () {

        "use strict";


        // Init Widget Demo JS
        // demoHighCharts.init();

        // Because we are using Admin Panels we use the OnFinish 
        // callback to activate the demoWidgets. It's smoother if
        // we let the panels be moved and organized before 
        // filling them with content from various plugins

        // Init plugins used on this page
        // HighCharts, JvectorMap, Admin Panels

        // Init Admin Panels on widgets inside the ".admin-panels" container
        $('.admin-panels').adminpanel({
            grid: '.admin-grid',
            draggable: true,
            preserveGrid: true,
            mobile: false,
            callback: function () {
                bootbox.confirm('<h3>A Custom Callback!</h3>', function () {
                });
            },
            onFinish: function () {
                $('.admin-panels').addClass('animated fadeIn').removeClass('fade-onload');

                // Init the rest of the plugins now that the panels
                // have had a chance to be moved and organized.
                // It's less taxing to organize empty panels
                demoHighCharts.init();
                runVectorMaps();

                // We also refresh any "in-view" waypoints to ensure
                // the correct position is being calculated after the 
                // Admin Panels plugin moved everything
                Waypoint.refreshAll();

            },
            onSave: function () {
                $(window).trigger('resize');
            }
        });

        // Widget VectorMap
        function runVectorMaps() {

            // Jvector Map Plugin
            var runJvectorMap = function () {
                // Data set
                var mapData = [900, 700, 350, 500];
                // Init Jvector Map
                $('#WidgetMap').vectorMap({
                    map: 'us_lcc_en',
                    //regionsSelectable: true,
                    backgroundColor: 'transparent',
                    series: {
                        markers: [{
                                attribute: 'r',
                                scale: [3, 7],
                                values: mapData
                            }]
                    },
                    regionStyle: {
                        initial: {
                            fill: '#E5E5E5'
                        },
                        hover: {
                            "fill-opacity": 0.3
                        }
                    },
                    markers: [{
                            latLng: [37.78, -122.41],
                            name: 'San Francisco,CA'
                        }, {
                            latLng: [36.73, -103.98],
                            name: 'Texas,TX'
                        }, {
                            latLng: [38.62, -90.19],
                            name: 'St. Louis,MO'
                        }, {
                            latLng: [40.67, -73.94],
                            name: 'New York City,NY'
                        }],
                    markerStyle: {
                        initial: {
                            fill: '#a288d5',
                            stroke: '#b49ae0',
                            "fill-opacity": 1,
                            "stroke-width": 10,
                            "stroke-opacity": 0.3,
                            r: 3
                        },
                        hover: {
                            stroke: 'black',
                            "stroke-width": 2
                        },
                        selected: {
                            fill: 'blue'
                        },
                        selectedHover: {}
                    },
                });
                // Manual code to alter the Vector map plugin to 
                // allow for individual coloring of countries
                var states = ['US-CA', 'US-TX', 'US-MO',
                    'US-NY'
                ];
                var colors = [bgWarningLr, bgPrimaryLr, bgInfoLr, bgAlertLr];
                var colors2 = [bgWarning, bgPrimary, bgInfo, bgAlert];
                $.each(states, function (i, e) {
                    $("#WidgetMap path[data-code=" + e + "]").css({
                        fill: colors[i]
                    });
                });
                $('#WidgetMap').find('.jvectormap-marker')
                        .each(function (i, e) {
                            $(e).css({
                                fill: colors2[i],
                                stroke: colors2[i]
                            });
                        });
            }

            if ($('#WidgetMap').length) {
                runJvectorMap();
            }
        }

    });
</script>
JS;
$this->inlineScript()->captureEnd();