<header class="navbar navbar-fixed-top bg-light">
    <div class="navbar-branding">
        <a class="navbar-brand" href="<?php echo $this->basePath().'/admin' ?>"> <b>Pide Rapido</b> Admin
        </a>
        <span id="toggle_sidemenu_l" class="glyphicons glyphicons-show_lines"></span>
        <ul class="nav navbar-nav pull-right hidden">
            <li>
                <a href="#" class="sidebar-menu-toggle">
                    <span class="octicon octicon-ruby fs20 mr10 pull-right "></span>
                </a>
            </li>
        </ul>
    </div>

    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle fw600 p15" data-toggle="dropdown">
                <span>Hola, <?php echo $this->userIdentity->firstname; ?> <?php echo $this->userIdentity->lastname; ?> </span>
                <span class="caret caret-tp hidden-xs"></span>
            </a>
            <ul class="dropdown-menu dropdown-persist pn w250 bg-white" role="menu">
                <li class="br-t of-h">
                    <a href="#" class="fw600 p12 animated animated-short fadeInDown">
                        <span class="fa fa-gear pr5"></span> Configuración de Cuenta </a>
                </li>
                <li class="br-t of-h">
                    <a href="<?php echo $this->url('admin', array('controller' => 'login', 'action' => 'logout')) ?>" class="fw600 p12 animated animated-short fadeInDown">
                        <span class="fa fa-power-off pr5"></span> Cerrar sesión </a>
                </li>
            </ul>
        </li>
    </ul>

</header>