<footer>

  <div class="footer" id="footer">

    <div class="container">

      <div class="row">



        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">

          <h3> Soporte </h3>

          <ul>

            <li class="supportLi">

              <h4>D'Alvano Rapid Company C.A </h4>

              <br>

              <h5>Av. Pauji Residencia Serranillo 7B Caracas - Los Naranjos.</h5>

              <p> Contáctenos a través de: </p>

              <h4> <a class="inline" href="callto:+58 212 4356474"> <strong> <i class="fa fa-phone"> </i> +58 212 4356474 </strong> </a> </h4>

              <h4> <a class="inline" href="mailto:soporte@piderapido.com"> <i class="fa fa-envelope-o"> </i> soporte@piderapido.com </a> </h4>

            </li>

          </ul>

        </div>

         <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">

          <h3> Afiliaciones </h3>

          <ul>

            <li class="supportLi">

              <p> Para afiliar tu franquicia: </p>

              <h4> <a class="inline" href="callto:+58 212 4356474"> <strong> <i class="fa fa-phone"> </i> +58 212 4356474 </strong> </a> </h4>

              <h4> <a class="inline" href="mailto:info@piderapido.com"> <i class="fa fa-envelope-o"> </i> info@piderapido.com </a> </h4>

            </li>

          </ul>

        </div>

        

		<div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">

          <h3> Información </h3>

			

			      <ul class="unstyled">	

      				<li class="no-border">

                      

                      </li>

      					<a href="<?php echo $this->basePath() . '/catalog/franchise/list' ?>"><li> Encuéntralo </li></a>

      					<a href="terminos.pdf"><li>Términos y condiciones </li></a>

      					<!--li> Políticas de Privacidad  </li-->

            </ul>

			

		</div>

		

    <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">

      <h3> Mantente en Contacto </h3>

      <ul class="social">

        <center>

            <li> 
                <a href="https://www.facebook.com/Pide-R%C3%A1pido-1553920374896633/" target="_blank">
                    <img class="top" src="<?php echo $this->basePath('img') ?>/social/facebookrojo.png" />
                </a>
            </li>
            <li> 
                <a href="https://www.instagram.com/piderapido/" target="_blank">
                    <img class="top" src="<?php echo $this->basePath('img') ?>/social/instagramrojo.png" />
                </a>
            </li>
            <li> 
                <a href="https://twitter.com/piderapido" target="_blank">
                    <img class="top" src="<?php echo $this->basePath('img') ?>/social/twitterrojo.png" />
                </a>
            </li>

            <li>  
                <a href="https://www.youtube.com/channel/UCaW4eyI65cTrLTWWRRIlZjQ" target="_blank">
                    <img class="top" src="<?php echo $this->basePath('img') ?>/social/youtuberojo.png" />
                </a>
            </li>

        </center>

      </ul>       
      <div id="fb" class="col-md-2 col-xs-2">
       
      </div>

     

   

      <div id="fb" class="col-md-2">
  
      </div>

     

     

     

      

    </div>

      </div>

      <!--/.row--> 

    </div>

    <!--/.container--> 

  </div>

  <!--/.footer-->

  

  <div class="footer-bottom">

    <div class="container">

      <p class="pull-left"> &copy; Pide Rápido 2015. Derechos reservados. </p>

      <div class="pull-right paymentMethodImg"> <img height="30" class="pull-right" src="<?php echo $this->basePath('img') ?>/site/payment/master_card.png" alt="img"> <!--img height="30" class="pull-right" src="<?php echo $this->basePath('img') ?>/site/payment/paypal.png" alt="img"--> <img height="30" class="pull-right" src="<?php echo $this->basePath('img') ?>/site/payment/american_express_card.png" alt="img"> <!--img height="30" class="pull-right" src="<?php echo $this->basePath('img') ?>/site/payment/discover_network_card.png" alt="img"--> <!--img height="30" class="pull-right" src="<?php echo $this->basePath('img') ?>/site/payment/google_wallet.png" alt="img"--> </div>

    </div>

  </div>

  <!--/.footer-bottom--> 

</footer>