<!DOCTYPE html>
<html>
    <?php echo $this->partial('layout/franchise_head'); ?>
    <body class="external-page sb-l-c sb-r-c">

            <?php echo $this->content; ?>

        <!-- jQuery -->

        <script type="text/javascript" src="<?php echo $this->basePath('vendor') ?>/jquery/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('vendor') ?>/jquery/jquery_ui/jquery-ui.min.js"></script>
        <!-- Jquery debounce -->
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/bootstrap/bootstrap.min.js"></script>

        <!-- Page Plugins -->
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/pages/login/EasePack.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/pages/login/rAF.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/pages/login/TweenLite.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/pages/login/login.js"></script>

        <!-- Theme Javascript-->
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/utility/utility.js"></script> 
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/main.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/demo.js"></script>

        <!-- END: PAGE SCRIPTS -->

    </body>

</html>
