<aside id="sidebar_left" class="nano nano-primary">
    <div class="nano-content">

        <!-- Start: Sidebar Header -->
        <header class="sidebar-header">
            <div class="user-menu">
                <div class="row text-center mbn">
                    <div class="col-xs-4">
                        <a href="dashboard.html" class="text-primary" data-toggle="tooltip" data-placement="top" title="Dashboard">
                            <span class="glyphicons glyphicons-home"></span>
                        </a>
                    </div>
                    <div class="col-xs-4">
                        <a href="pages_messages.html" class="text-info" data-toggle="tooltip" data-placement="top" title="Messages">
                            <span class="glyphicons glyphicons-inbox"></span>
                        </a>
                    </div>
                    <div class="col-xs-4">
                        <a href="pages_profile.html" class="text-alert" data-toggle="tooltip" data-placement="top" title="Tasks">
                            <span class="glyphicons glyphicons-bell"></span>
                        </a>
                    </div>
                    <div class="col-xs-4">
                        <a href="pages_timeline.html" class="text-system" data-toggle="tooltip" data-placement="top" title="Activity">
                            <span class="glyphicons glyphicons-imac"></span>
                        </a>
                    </div>
                    <div class="col-xs-4">
                        <a href="pages_profile.html" class="text-danger" data-toggle="tooltip" data-placement="top" title="Settings">
                            <span class="glyphicons glyphicons-settings"></span>
                        </a>
                    </div>
                    <div class="col-xs-4">
                        <a href="pages_gallery.html" class="text-warning" data-toggle="tooltip" data-placement="top" title="Cron Jobs">
                            <span class="glyphicons glyphicons-restart"></span>
                        </a>
                    </div>
                </div>
            </div>
        </header>
        <!-- End: Sidebar Header -->

        <!-- sidebar menu -->
        <ul class="nav sidebar-menu">           
            <li class="sidebar-label pt15">Acciones 
                
            
            </li>
           
            <li>
                <a href="<?php echo $this->url('franchise', array('controller' => 'orders', 'action' => 'index')) ?>">
                    <span class="glyphicons glyphicons-home"></span>
                    <span class="sidebar-title">Pedidos</span>
                    <!-- <span class="caret"></span> -->
                </a>

            </li>
            <li>
                <a class="accordion-toggle" href="#">
                    <span class="glyphicons glyphicons-parents"></span>
                    <span class="sidebar-title">Facturas</span>
                    <span class="caret"></span>
                </a>
                <ul class="nav sub-nav">
                    <li>
                        <a href="<?php echo $this->url('franchise', array('controller' => 'invoice', 'action' => 'invoiceDaily')) ?>">
                            <span class="fa fa-calendar-o"></span> Diaria</a>
                    </li>            
                    <li>
                        <a href="<?php echo $this->url('franchise', array('controller' => 'invoice', 'action' => 'invoiceMonthly')) ?>">
                            <span class="glyphicons glyphicons-calendar"></span> Mensual </a>
                    </li>
<!--                    <li>
                        <a href="fpersonalizado.php">
                            <span class="glyphicons glyphicons-edit"></span>Personalizado</a>
                    </li>-->
                </ul>  
            </li>
            <li>
                <a class="accordion-toggle" href="#">
                    <span class="glyphicons glyphicons-fast_food"></span>
                    <span class="sidebar-title">Disponibilidad</span>
                    <span class="caret"></span>
                </a>
                <ul class="nav sub-nav">
                    <li>
                        <a href="<?php echo $this->url('franchise', array('controller' => 'products', 'action' => 'products')) ?>">
                            <span class="glyphicons glyphicons-fast_food"></span> Combos</a>
                    </li>
                </ul> 

            </li>
            <li>
                <a class="accordion-toggle" href="#">
                    <span class="glyphicons glyphicons-fast_food"></span>
                    <span class="sidebar-title">Operadores</span>
                    <span class="caret"></span>
                </a>
                <ul class="nav sub-nav">
                    <li>
                        <a href="<?php echo $this->url('franchise', array('controller' => 'operator', 'action' => 'add')) ?>">
                            <span class="glyphicons glyphicons-fast_food"></span> Crear Operador</a>
                    </li>            
                    <li>
                        <a href="<?php echo $this->url('franchise', array('controller' => 'operator', 'action' => 'list')) ?>">
                            <span class="glyphicons glyphicons-fast_food"></span>Operadores</a>
                    </li>
                </ul> 

            </li>
            <li>
                <a href="<?php echo $this->url('franchise', array('controller' => 'index', 'action' => 'edit', 'id' => $this->userIdentity->branch_id)); ?>">
                    <span class="glyphicons glyphicons-folder_open"></span>
                    <span class="sidebar-title">Ajustes</span>

                </a>

            </li>
            <li>
                 <a title="Volver atrás" href="javascript:window.history.back();" style="/* float: left; */margin-right: 5px;" class="sidebar-label ">
                       volver

                    </a>
            </li>
        </ul>
     
       
    </div>
</aside>

