<section id="content" class="animated fadeIn">

    <h2 class="lh30 mtn text-center">Busqueda de <b class="text-primary">Consumos</b></h2>
    <br>

    <div class="panel">

        <div class="admin-form theme-primary">

            <div id="p1" class="panel heading-border panel-primary">

                <div class="panel-body bg-light">
                    <form method="post" action="" id="form-ui" class="form-horizontal">

                        <br><br>

                        <!-- Multi Selects -->
                        <div class="row">
                            <div class="col-md-4 col-md-offset-4 text-center">
                                <div class="section">
                                    <label class="field prepend-icon">
                                        <input type="email" name="email" id="email" class="gui-input" placeholder="Ingresa Email">
                                        <label for="email" class="field-icon"><i class="fa fa-envelope"></i>
                                        </label>
                                    </label>
                                </div>
                            </div>
<!--                            <div class="col-md-4 text-center">
                                <div class="section">
                                    <label class="field prepend-icon">
                                        <input type="text" name="email" id="text" class="gui-input" placeholder="Ingresa Cedula">
                                        <label for="text" class="field-icon"><i class="fa fa-user"></i>
                                        </label>
                                    </label>
                                </div>
                            </div>
                            <div class="col-md-4 text-center">
                                <div class="section">
                                    <div class="form-group">
                                        <label for="monthpicker1" class="field prepend-icon">
                                            <input type="text" id="monthpicker1" name="monthpicker1" class="gui-input">
                                            <label class="field-icon"><i class="fa fa-calendar-o"></i>
                                            </label>
                                        </label>
                                    </div>
                                </div>
                            </div>-->
                        </div>
                        <div class="col-md-12 text-center">
                            <center>
                                <button class="button btn-primary" type="button" style="color: #666666;">Generar Búsqueda</button>
                            </center>
                        </div>

                    </form> 
                </div>
            </div>
        </div>                         
    </div>                        

    <div class="col-md-12">

        <div class="panel">
            <div class="panel-body pn">

                <table class="table admin-form theme-warning tc-checkbox-1 fs13">
                    <thead>
                        <tr class="bg-light">
                            <th class="text-center">ID</th>
                            <th class="">Primer Nombre</th>
                            <th class="">Apellido </th>
                            <th class="">Cedula de Identidad</th>
                            <th class="">Email</th>
                            <th class="">Telefono</th>
                            <th class=""></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->customer as $customer) : ?>
                        <tr>
                            <td class=""><?php echo $customer->customer_id ?></td>
                            <td class=""><?php echo $customer->firstname ?></td>
                            <td class=""><?php echo $customer->lastname ?></td>
                            <td class=""><?php echo $customer->document_identity ?></td>
                            <td class=""><?php echo $customer->email ?></td>
                            <td class=""><?php echo $customer->telephone ?></td>
                            <td class=""><a href="<?php echo $this->url('admin', array('controller' => 'customer', 'action' => 'list', 'id' => $customer->customer_id)); ?>">Ver Ordenes</a></td>
                        </tr>
                        <?php endforeach; ?>

                    </tbody>
                </table>

            </div>
        </div>

    </div>



</section>
<!-- include footable plugin --> 

<?php $this->inlineScript()->appendFile($this->basePath('assets/js/jquery-tcm-month.js')); ?>

<?php
$this->inlineScript()->captureStart();

echo <<<JS
    $(function() {
        "use strict";

            /* @month picker
            *  ------------------------------------------------------------------
            */

            $("#monthpicker1").monthpicker({
                changeYear: false,
                stepYears: 1,
                prevText: '<i class="fa fa-chevron-left"></i>',
                nextText: '<i class="fa fa-chevron-right"></i>',
                showButtonPanel: false,
                dateFormat: "mm/yy",
                beforeShow: function(input, inst) {
                    var newclass = 'admin-form';
                    var themeClass = $(this).parents('.admin-form').attr('class');
                    var smartpikr = inst.dpDiv.parent();
                    if (!smartpikr.hasClass(themeClass)) {
                        inst.dpDiv.wrap('<div class="' + themeClass + '"></div>');
                    }
                }
            });

            $('.inline-mp').monthpicker({
                prevText: '<i class="fa fa-chevron-left"></i>',
                nextText: '<i class="fa fa-chevron-right"></i>',
                showButtonPanel: false
            });
    });
JS;

$this->inlineScript()->captureEnd();
?>