<div class="row">

    <div class="col-lg-12 col-md-9 col-sm-7">

        <div class="row userInfo">

            <div class="col-xs-12 col-sm-3">
                
            </div>
            <div class="col-xs-12 col-sm-offset-1 col-sm-3">
                <form action="<?php echo $this->url('account', array('controller' => 'login', 'action' => 'forget')) ?>" method="post">
                <h2 class="block-title-2"><span>Restablecer Contraseña</span></h2>
                
                    <div class="form-group">
                        <label>Nuevo Password</label>
                         <?php echo $this->formInput($this->forgetForm->get('password')); ?>
                    </div>
                    <div class="form-group">
                        <label>Repetir Password</label>
                        <?php echo $this->formInput($this->forgetForm->get('password2')); ?>
                    </div>
                  
                   <div>
                         <button type="submit" class="btn   btn-primary">Restablecer</button>
                       <?php echo $this->formInput($this->forgetForm->get('csrf')); ?>	
                       <?php echo $this->formInput($this->forgetForm->get('token')); ?>	
                      
                    </div>
                </form>
            </div>

            <div class="col-xs-12 col-sm-offset-1 col-sm-3">
              
            </div>
        </div>
        <!--/row end--> 

    </div>

</div> <!--/row-->
<?php
 $this->inlineScript()->captureStart();
            echo <<<JS
          
    var CaptchaCallback = function(){
        
        grecaptcha.render('re2', {'sitekey' : '6LctMxkTAAAAALJWle9jjS2yveGef9sgT5sGHupx'});
        grecaptcha.render('re3', {'sitekey' : '6LctMxkTAAAAALJWle9jjS2yveGef9sgT5sGHupx'});
    };
JS;
            $this->inlineScript()->captureEnd();