<!-- Begin: Content -->
<section id="content" class="animated fadeIn">
        <div class="row">

            <div class="text-center">

                <h2 class="lh30 mt15 text-center"> Productos por <b class="text-primary">Franquicias </b></h2>
                <br>
            </div>
        </div>
        <br>
        <?php foreach ($this->franchieses as $franchies) : ?>
            <a href="<?php echo $this->url('admin', array('controller' => 'product', 'action' => 'list', 'id' => $franchies->franchise_id)); ?>">
                <div class="col-md-4">
                    <div class="panel">
                        <div class="panel-heading">
                            <span class="panel-title">
                                <span class="glyphicons glyphicons-fast_food"></span>Productos de <?php echo $franchies->name ?></span>
                        </div>
                        <div class="panel-body">

                            <div class="clearfix"></div>
                            <div class="tab-content br-n pn">
                                <div id="tab17_1" class="tab-pane active">
                                    <div class="row">
                                        <div class="col-md-4 ">
                                            <img  src="<?php echo $this->basePath() . '/img/franchise/' . $franchies->logo ?>" class="img-responsive thumbnail mr25 h-100" />
                                        </div>
                                        <div class="col-md-8">
                                            <h5><?php echo $franchies->name ?></h5><br>
                                        </div>
                                    </div>
                                </div>                                    
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        <?php endforeach; ?>

</section>
<!-- End: Content -->