
<h2 class="lh30 mt15 text-center">
    <b class="text-primary">Operadores</b>
</h2>
<br>
<div class="col-md-12">
    <div class="admin-form">
        <div id="p1" class="panel heading-border">
            <div class="panel-body bg-light">
                <div class="row">
                    <div class="col-md-12">
                        <div class="section-divider mt40 mb25" id="spy4">
                            <span>Búqueda</span>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <form id="form"  action="<?php echo $this->basePath($this->operator_list->getAttribute('action')); ?>" method="post" enctype="multipart/form-data">
                        <div class="col-md-offset-4 col-md-4">
                            <div class="section">
                                <label class="field select">
                                    <?php echo $this->formSelect($this->operator_list->get('operator_id')); ?>
                                    <i class="arrow"></i>
                                </label>
                            </div>
                        </div>
                        <div class="col-md-12 text-center">
                            <center>
                                <button class="button btn-primary" type="submit">Buscar</button>
                            </center>
                        </div> 
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>					
</br>					
<div class="col-md-12">
    <div class="panel">
        <div class="panel-heading">
            <span class="panel-title">
                <span class="glyphicons glyphicons-fast_food"></span>Operador Nombre #1</span>
        </div>
        <div class="panel-body pn" id="tableCenter">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th><b><center>Nombre</center></b></th>
                        <th><b><center>Apellido</center></b></th>
                        <th><b><center>Email</center></b></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->operator as $operator) : ?>
                        <tr>                                
                            <td><?php echo $operator->name ?></td>
                            <td><?php echo $operator->last_name ?></td>                                        
                            <td><?php echo $operator->email ?></td>                                        
                            <td><a class="btn-delete"  href="<?php echo $this->url('franchise', array('controller' => 'operator', 'action' => 'delete', 'id' => $operator->operator_id)) ?>">Eliminar</a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>     
